let nombre1=prompt("Ingrese su nombre")
let Edad1=parseInt(prompt("Ingrese su edad"))
let nombre2=prompt("Ingrese su nombre")
let Edad2=parseInt(prompt("Ingrese su edad"))
let nombre3=prompt("Ingrese su nombre")
let Edad3=parseInt(prompt("Ingrese su edad"))

let maximo = Math.max(Edad1, Edad2,Edad3,)

if (maximo == Edad1 ) { alert("El mayor de los tres es " + nombre1)}
if (maximo == Edad2 ) { alert("El mayor de los tres es " + nombre2)}
if (maximo == Edad3 ) { alert("El mayor de los tres es " + nombre3)}
if (maximo == Edad3 && maximo == Edad2 && maximo == Edad1  ) { alert (" Todos tienen la misma edad ")}


    
